GET https://api.spotify.com/v1/playlists/4xKZLaPLh99LGKRjRlHxyX?si=83c968361f034f16/tracks
Authorization: Bearer BQDs1nBFsrHNKm5hXHILpuJijFZlWtru1RagImTeCF_kuWHiZ8aPrUrPvDFifGgcMWt78ao7kp89-I7Vie_cBaElUl5vVzBPqbkSTGuUW0y4Kvmf7YOvSNtv0TBybPkPdUFdk44nZY_8KQgHkFg6Xvyj_mELTiH-AS6CNCcrLdBIpRk3dDT62ckZ3XoV2hA3nPb6-VIdqVxVNymj
Content-Type: application/json

###

GET https://api.spotify.com/v1/tracks/5IWMWziGFffG8q0nBJXgYH
Authorization: Bearer BQDs1nBFsrHNKm5hXHILpuJijFZlWtru1RagImTeCF_kuWHiZ8aPrUrPvDFifGgcMWt78ao7kp89-I7Vie_cBaElUl5vVzBPqbkSTGuUW0y4Kvmf7YOvSNtv0TBybPkPdUFdk44nZY_8KQgHkFg6Xvyj_mELTiH-AS6CNCcrLdBIpRk3dDT62ckZ3XoV2hA3nPb6-VIdqVxVNymj
Content-Type: application/json